sudo: false

language: node_js

node_js:
  - node
  - 10
  - 8
  - 6

matrix:
  include:
    - node_js: node
      env: BROTLI=1
    - node_js: 6
      env: BROTLI=1
      before_install: npm i --save-only request brotli

before_install: npm i --save-only request
install: npm i
after_success: npm run coverage

notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
